workflows:
  flutter-test-workflow:
    name: Flutter Test Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      node: latest
      java: 11
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Run tests
        script: |
          flutter test
    artifacts:
      - build/**
    publishing:
      email:
        recipients:
          - abrham.wendmeneh.a@gmail.com