name: Widgetbook Cloud

on: push

permissions:
  contents: write

jobs:
  production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Bootstrap
        uses: ./.github/actions/bootstrap

      - name: Install Widgetbook CLI
        run: dart pub global activate widgetbook_cli

      - name: Upload Widgetbook
        working-directory: flutter_widgetbook
        run: widgetbook cloud build push --api-key ${{ secrets.WIDGETBOOK_CLOUD_API_KEY }}
